// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAERy7e693t6Qhr9k1zsPw6v9RaLc9Dl9k',
//     appId: '1:310077896070:web:8816d40ff70ba1d7f26807',
//     messagingSenderId: '310077896070',
//     projectId: 'bio-app-f31df',
//     authDomain: 'bio-app-f31df.firebaseapp.com',
//     storageBucket: 'bio-app-f31df.firebasestorage.app',
//     measurementId: 'G-6VWS0P4F6H',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDkhpCdzoqW4wbtM-iNj68vk2YwQz-96No',
//     appId: '1:310077896070:android:01991dadbb194a78f26807',
//     messagingSenderId: '310077896070',
//     projectId: 'bio-app-f31df',
//     storageBucket: 'bio-app-f31df.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDIsff7OH2QGZMbLdbbXsuY_SlOnqVCEz8',
//     appId: '1:310077896070:ios:327aa53de224948ff26807',
//     messagingSenderId: '310077896070',
//     projectId: 'bio-app-f31df',
//     storageBucket: 'bio-app-f31df.firebasestorage.app',
//     iosBundleId: 'com.example.bioApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDIsff7OH2QGZMbLdbbXsuY_SlOnqVCEz8',
//     appId: '1:310077896070:ios:327aa53de224948ff26807',
//     messagingSenderId: '310077896070',
//     projectId: 'bio-app-f31df',
//     storageBucket: 'bio-app-f31df.firebasestorage.app',
//     iosBundleId: 'com.example.bioApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAERy7e693t6Qhr9k1zsPw6v9RaLc9Dl9k',
//     appId: '1:310077896070:web:00e4a0f6db69afc2f26807',
//     messagingSenderId: '310077896070',
//     projectId: 'bio-app-f31df',
//     authDomain: 'bio-app-f31df.firebaseapp.com',
//     storageBucket: 'bio-app-f31df.firebasestorage.app',
//     measurementId: 'G-08MF6V2G82',
//   );

// }
